//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoCaoDoanhThu
    {
        public string Mã_hóa_đơn { get; set; }
        public int Tổng_tiền { get; set; }
        public System.DateTime Ngày_tạo { get; set; }
        public string Mã_khách_hàng { get; set; }
    }
}
