//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class calamviec
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public calamviec()
        {
            this.chi_tiet_luong_nv = new HashSet<chi_tiet_luong_nv>();
        }
    
        public string ma_ca { get; set; }
        public string ten_ca { get; set; }
        public System.TimeSpan gio_bd { get; set; }
        public System.TimeSpan gio_kt { get; set; }
        public int so_tien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chi_tiet_luong_nv> chi_tiet_luong_nv { get; set; }
    }
}
