//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CoffeeEntities : DbContext
    {
        public CoffeeEntities()
            : base("name=CoffeeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ban> bans { get; set; }
        public virtual DbSet<calamviec> calamviecs { get; set; }
        public virtual DbSet<chi_tiet_ban_hang> chi_tiet_ban_hang { get; set; }
        public virtual DbSet<chi_tiet_luong_nv> chi_tiet_luong_nv { get; set; }
        public virtual DbSet<hanghoa> hanghoas { get; set; }
        public virtual DbSet<hoadon> hoadons { get; set; }
        public virtual DbSet<khachhang> khachhangs { get; set; }
        public virtual DbSet<loaihang> loaihangs { get; set; }
        public virtual DbSet<nhanvien> nhanviens { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<BaoCaoDoanhThu> BaoCaoDoanhThus { get; set; }
        public virtual DbSet<view_Ban> view_Ban { get; set; }
        public virtual DbSet<view_DoUong> view_DoUong { get; set; }
        public virtual DbSet<view_KhachHang> view_KhachHang { get; set; }
        public virtual DbSet<view_NhanVien> view_NhanVien { get; set; }
        public virtual DbSet<view_Users> view_Users { get; set; }
    
        [DbFunction("CoffeeEntities", "func_timDoUongTheoTen")]
        public virtual IQueryable<func_timDoUongTheoTen_Result> func_timDoUongTheoTen(string tenDoUong)
        {
            var tenDoUongParameter = tenDoUong != null ?
                new ObjectParameter("TenDoUong", tenDoUong) :
                new ObjectParameter("TenDoUong", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<func_timDoUongTheoTen_Result>("[CoffeeEntities].[func_timDoUongTheoTen](@TenDoUong)", tenDoUongParameter);
        }
    
        public virtual int ban_delete(string ma_ban)
        {
            var ma_banParameter = ma_ban != null ?
                new ObjectParameter("ma_ban", ma_ban) :
                new ObjectParameter("ma_ban", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ban_delete", ma_banParameter);
        }
    
        public virtual int ban_insert(string ma_ban, string ten_ban, string thuoc_tinh)
        {
            var ma_banParameter = ma_ban != null ?
                new ObjectParameter("ma_ban", ma_ban) :
                new ObjectParameter("ma_ban", typeof(string));
    
            var ten_banParameter = ten_ban != null ?
                new ObjectParameter("ten_ban", ten_ban) :
                new ObjectParameter("ten_ban", typeof(string));
    
            var thuoc_tinhParameter = thuoc_tinh != null ?
                new ObjectParameter("thuoc_tinh", thuoc_tinh) :
                new ObjectParameter("thuoc_tinh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ban_insert", ma_banParameter, ten_banParameter, thuoc_tinhParameter);
        }
    
        public virtual ObjectResult<ban_selectall_Result> ban_selectall()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ban_selectall_Result>("ban_selectall");
        }
    
        public virtual int ban_update(string ma_ban, string ten_ban, string thuoc_tinh)
        {
            var ma_banParameter = ma_ban != null ?
                new ObjectParameter("ma_ban", ma_ban) :
                new ObjectParameter("ma_ban", typeof(string));
    
            var ten_banParameter = ten_ban != null ?
                new ObjectParameter("ten_ban", ten_ban) :
                new ObjectParameter("ten_ban", typeof(string));
    
            var thuoc_tinhParameter = thuoc_tinh != null ?
                new ObjectParameter("thuoc_tinh", thuoc_tinh) :
                new ObjectParameter("thuoc_tinh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ban_update", ma_banParameter, ten_banParameter, thuoc_tinhParameter);
        }
    
        public virtual int douong_delete(string ma_hh)
        {
            var ma_hhParameter = ma_hh != null ?
                new ObjectParameter("ma_hh", ma_hh) :
                new ObjectParameter("ma_hh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("douong_delete", ma_hhParameter);
        }
    
        public virtual int douong_insert(string ma_hh, string ten_hh, Nullable<int> soluong, Nullable<int> gia_sp, string ma_lh)
        {
            var ma_hhParameter = ma_hh != null ?
                new ObjectParameter("ma_hh", ma_hh) :
                new ObjectParameter("ma_hh", typeof(string));
    
            var ten_hhParameter = ten_hh != null ?
                new ObjectParameter("ten_hh", ten_hh) :
                new ObjectParameter("ten_hh", typeof(string));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("soluong", soluong) :
                new ObjectParameter("soluong", typeof(int));
    
            var gia_spParameter = gia_sp.HasValue ?
                new ObjectParameter("gia_sp", gia_sp) :
                new ObjectParameter("gia_sp", typeof(int));
    
            var ma_lhParameter = ma_lh != null ?
                new ObjectParameter("ma_lh", ma_lh) :
                new ObjectParameter("ma_lh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("douong_insert", ma_hhParameter, ten_hhParameter, soluongParameter, gia_spParameter, ma_lhParameter);
        }
    
        public virtual ObjectResult<douong_selectall_Result> douong_selectall()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<douong_selectall_Result>("douong_selectall");
        }
    
        public virtual int douong_update(string ma_hh, string ten_hh, Nullable<int> soluong, Nullable<int> gia_sp, string ma_lh)
        {
            var ma_hhParameter = ma_hh != null ?
                new ObjectParameter("ma_hh", ma_hh) :
                new ObjectParameter("ma_hh", typeof(string));
    
            var ten_hhParameter = ten_hh != null ?
                new ObjectParameter("ten_hh", ten_hh) :
                new ObjectParameter("ten_hh", typeof(string));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("soluong", soluong) :
                new ObjectParameter("soluong", typeof(int));
    
            var gia_spParameter = gia_sp.HasValue ?
                new ObjectParameter("gia_sp", gia_sp) :
                new ObjectParameter("gia_sp", typeof(int));
    
            var ma_lhParameter = ma_lh != null ?
                new ObjectParameter("ma_lh", ma_lh) :
                new ObjectParameter("ma_lh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("douong_update", ma_hhParameter, ten_hhParameter, soluongParameter, gia_spParameter, ma_lhParameter);
        }
    
        public virtual int khachhang_delete(string ma_kh)
        {
            var ma_khParameter = ma_kh != null ?
                new ObjectParameter("ma_kh", ma_kh) :
                new ObjectParameter("ma_kh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("khachhang_delete", ma_khParameter);
        }
    
        public virtual int khachhang_insert(string ma_kh, string ten_kh, string diachi, string sdt)
        {
            var ma_khParameter = ma_kh != null ?
                new ObjectParameter("ma_kh", ma_kh) :
                new ObjectParameter("ma_kh", typeof(string));
    
            var ten_khParameter = ten_kh != null ?
                new ObjectParameter("ten_kh", ten_kh) :
                new ObjectParameter("ten_kh", typeof(string));
    
            var diachiParameter = diachi != null ?
                new ObjectParameter("diachi", diachi) :
                new ObjectParameter("diachi", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("khachhang_insert", ma_khParameter, ten_khParameter, diachiParameter, sdtParameter);
        }
    
        public virtual ObjectResult<khachhang_selectall_Result> khachhang_selectall()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<khachhang_selectall_Result>("khachhang_selectall");
        }
    
        public virtual int khachhang_update(string ma_kh, string ten_kh, string diachi, string sdt)
        {
            var ma_khParameter = ma_kh != null ?
                new ObjectParameter("ma_kh", ma_kh) :
                new ObjectParameter("ma_kh", typeof(string));
    
            var ten_khParameter = ten_kh != null ?
                new ObjectParameter("ten_kh", ten_kh) :
                new ObjectParameter("ten_kh", typeof(string));
    
            var diachiParameter = diachi != null ?
                new ObjectParameter("diachi", diachi) :
                new ObjectParameter("diachi", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("khachhang_update", ma_khParameter, ten_khParameter, diachiParameter, sdtParameter);
        }
    
        public virtual int loaihang_insert(string ma_lh, string ten_lh, string mo_ta)
        {
            var ma_lhParameter = ma_lh != null ?
                new ObjectParameter("ma_lh", ma_lh) :
                new ObjectParameter("ma_lh", typeof(string));
    
            var ten_lhParameter = ten_lh != null ?
                new ObjectParameter("ten_lh", ten_lh) :
                new ObjectParameter("ten_lh", typeof(string));
    
            var mo_taParameter = mo_ta != null ?
                new ObjectParameter("mo_ta", mo_ta) :
                new ObjectParameter("mo_ta", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("loaihang_insert", ma_lhParameter, ten_lhParameter, mo_taParameter);
        }
    
        public virtual int nhanvien_delete(string ma_nv)
        {
            var ma_nvParameter = ma_nv != null ?
                new ObjectParameter("ma_nv", ma_nv) :
                new ObjectParameter("ma_nv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("nhanvien_delete", ma_nvParameter);
        }
    
        public virtual int nhanvien_insert(string ma_nv, string ten_nv, string diachi, string sdt, string chucvu, string gioitinh, Nullable<System.DateTime> ngay_vao_lam)
        {
            var ma_nvParameter = ma_nv != null ?
                new ObjectParameter("ma_nv", ma_nv) :
                new ObjectParameter("ma_nv", typeof(string));
    
            var ten_nvParameter = ten_nv != null ?
                new ObjectParameter("ten_nv", ten_nv) :
                new ObjectParameter("ten_nv", typeof(string));
    
            var diachiParameter = diachi != null ?
                new ObjectParameter("diachi", diachi) :
                new ObjectParameter("diachi", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            var chucvuParameter = chucvu != null ?
                new ObjectParameter("chucvu", chucvu) :
                new ObjectParameter("chucvu", typeof(string));
    
            var gioitinhParameter = gioitinh != null ?
                new ObjectParameter("gioitinh", gioitinh) :
                new ObjectParameter("gioitinh", typeof(string));
    
            var ngay_vao_lamParameter = ngay_vao_lam.HasValue ?
                new ObjectParameter("ngay_vao_lam", ngay_vao_lam) :
                new ObjectParameter("ngay_vao_lam", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("nhanvien_insert", ma_nvParameter, ten_nvParameter, diachiParameter, sdtParameter, chucvuParameter, gioitinhParameter, ngay_vao_lamParameter);
        }
    
        public virtual ObjectResult<nhanvien_selectall_Result> nhanvien_selectall()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<nhanvien_selectall_Result>("nhanvien_selectall");
        }
    
        public virtual int nhanvien_update(string ma_nv, string ten_nv, string diachi, string sdt, string chucvu, string gioitinh, Nullable<System.DateTime> ngay_vao_lam)
        {
            var ma_nvParameter = ma_nv != null ?
                new ObjectParameter("ma_nv", ma_nv) :
                new ObjectParameter("ma_nv", typeof(string));
    
            var ten_nvParameter = ten_nv != null ?
                new ObjectParameter("ten_nv", ten_nv) :
                new ObjectParameter("ten_nv", typeof(string));
    
            var diachiParameter = diachi != null ?
                new ObjectParameter("diachi", diachi) :
                new ObjectParameter("diachi", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            var chucvuParameter = chucvu != null ?
                new ObjectParameter("chucvu", chucvu) :
                new ObjectParameter("chucvu", typeof(string));
    
            var gioitinhParameter = gioitinh != null ?
                new ObjectParameter("gioitinh", gioitinh) :
                new ObjectParameter("gioitinh", typeof(string));
    
            var ngay_vao_lamParameter = ngay_vao_lam.HasValue ?
                new ObjectParameter("ngay_vao_lam", ngay_vao_lam) :
                new ObjectParameter("ngay_vao_lam", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("nhanvien_update", ma_nvParameter, ten_nvParameter, diachiParameter, sdtParameter, chucvuParameter, gioitinhParameter, ngay_vao_lamParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int users_delete(string iD)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("users_delete", iDParameter);
        }
    
        public virtual int users_insert(string iD, string ten, string userName, string passWord, string phanquyen)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("Ten", ten) :
                new ObjectParameter("Ten", typeof(string));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var passWordParameter = passWord != null ?
                new ObjectParameter("PassWord", passWord) :
                new ObjectParameter("PassWord", typeof(string));
    
            var phanquyenParameter = phanquyen != null ?
                new ObjectParameter("phanquyen", phanquyen) :
                new ObjectParameter("phanquyen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("users_insert", iDParameter, tenParameter, userNameParameter, passWordParameter, phanquyenParameter);
        }
    
        public virtual ObjectResult<users_selectall_Result> users_selectall()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<users_selectall_Result>("users_selectall");
        }
    
        public virtual int users_update(string iD, string ten, string userName, string passWord, string phanquyen)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("Ten", ten) :
                new ObjectParameter("Ten", typeof(string));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var passWordParameter = passWord != null ?
                new ObjectParameter("PassWord", passWord) :
                new ObjectParameter("PassWord", typeof(string));
    
            var phanquyenParameter = phanquyen != null ?
                new ObjectParameter("phanquyen", phanquyen) :
                new ObjectParameter("phanquyen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("users_update", iDParameter, tenParameter, userNameParameter, passWordParameter, phanquyenParameter);
        }
    }
}
