//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class nhanvien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nhanvien()
        {
            this.chi_tiet_luong_nv = new HashSet<chi_tiet_luong_nv>();
            this.hoadons = new HashSet<hoadon>();
        }
    
        public string ma_nv { get; set; }
        public string ten_nv { get; set; }
        public string diachi { get; set; }
        public string sdt { get; set; }
        public string chucvu { get; set; }
        public string gioitinh { get; set; }
        public System.DateTime ngay_vao_lam { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chi_tiet_luong_nv> chi_tiet_luong_nv { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hoadon> hoadons { get; set; }
        public virtual user user { get; set; }
    }
}
