//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public string ID { get; set; }
        public string Ten { get; set; }
        public string UserName { get; set; }
        public string PassWord { get; set; }
        public string phanquyen { get; set; }
    
        public virtual nhanvien nhanvien { get; set; }
    }
}
