//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_DoUong
    {
        public string Mã_Đồ_Uống { get; set; }
        public string Tên_Đồ_Uống { get; set; }
        public int Số_Lượng { get; set; }
        public int Giá { get; set; }
        public string Danh_Mục { get; set; }
    }
}
