//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_Ban
    {
        public string Mã_Bàn { get; set; }
        public string Tên_Bàn { get; set; }
        public string Thuộc_Tính { get; set; }
    }
}
